name: Fetch latest data and deploy with Datasette

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '15 22 * * 3,6'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Copy old csv file
      run: |
        cp data/malaskar.csv malaskrar-old.csv
    - name: Build database and csv
      run: python scraper.py
    - name: Create commit message
        run: csv-diff data/malaskrar-old.csv data/malaskrar.csv > message.txt
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel data/malaskrar.db \
          --token $VERCEL_TOKEN \
          --project malaskrar \
          --title "Málaskrár ráðuneyta" \
          --about "Málaskrár ráðuneyta - uppfært tvisvar í viku" \
          --about_url "https://github.com/pallih/malaskrar"
    - name: Commit changes
        run: |
          git add data/malaskrar.csv
          git add data/malaskrar.db
          git config --global user.email "malaskrarbot@example.com"
          git config --global user.name "Málaskrár þjarkur"
          git commit -F message.txt
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    # - uses: stefanzweifel/git-auto-commit-action@v4
